---
- name: deploy spring boot application 
  hosts: all 
  become: yes 
  tasks: 
    - name: update and install java
      apt: 
        name: openjdk-11-jdk
        update_cache:  yes
        state: present 
    - name: create a directory for springpetclinic
      file: 
        path: /usr/share/springpetclinic
        state: directory
    - name: Download and copy the file
      get_url: 
        url: https://referenceapplicationskhaja.s3-us-west-2.amazonaws.com/spring-petclinic-2.4.2.jar
        path: /usr/share/springpetclinic/spring-petclinic-2.4.2.jar